# 该文件及其参数配置仅适配 real_data 项目下的使用
name: "param_3"

# 数据文件路径
# 该数据文件未经过异常处理，将动作归类于 8 到 30 步长为 2
data_path: 'C:\Users\admi\Desktop\aaa\data\process\25_0322-0327_single_filter.csv'

# 环境设定
environment:

  init_valve: 11                # 初始阀门开度
  prev_valve: 11                # 初始上一次的阀门开度

  state:
    prev_valve: 11              # 初始阀门开度
    init_data_index: 0          # 从第一行开始读取
    history_window: 679         # 存储最近679个浓度值 5.3s读一次，3600s=1h

    scale: 1                   # 标准化的缩放系数 范围 (1 --> +∞)
    # 需要数据缩放的特征
    process:
      &common_state
      - "焦炉煤气阀门开度"
      - "指标"
      - "煤气压力1热风炉气动阀1前"
      - "GGH原烟气侧出口温度"
      - "CEM_脱硝入口烟气流量（工况）"
      - "入口NO2浓度（折算）"

    # 需要的状态
    features:
      - *common_state

  action:
    action_min: 8           # 阀门开度最小值
    action_max: 30          # 阀门开度最大值
    action_step: 1          # 阀门开度间隔

  reward:
    emission_weight: 0.85   # 排放权重
    valve_weight: 0.15      # 阀门开度权重
    pos_scale: 10          # 正向奖励缩放系数 范围 (1 --> +∞)
    neg_clip: -50          # 负向奖励阶段值

    sigma: 3                # 控制安全区奖励衰减速度，值越小对接近目标越敏感
    k: 5                    # 超限惩罚强度，超限 1 单位的惩罚=安全区最大奖励的 k 倍
    c: 0                    # 动作变化惩罚系数，抑制频繁调整（单步动作变化 ${action_step} 单位时，惩罚 $ {c * action_step}


dqn:
  train:
    name: "train"
    <<: &common_dqn
      hidden_layer: [ 128, 64, 64, 32 ]  # 每层隐藏层的大小
      device: "cuda"                # device可选值 ["cuda", "cpu"]
    epsilon_start: 1.0              # 开始的贪婪值
    epsilon_end: 0.01               # 最小的贪婪值
    epsilon_delay: 100000           # 贪婪缩放因子
    capacity: 10000                 # replay_memory容量
    lr: 0.0001                      # 学习率
    gamma: 0.9                      # 折扣率
    update_step: 1000               # target 网络更新间隔
    start_size: 3000                # 开始训练的最小数据量
    batch_size: 256                 # 每次更新网络处理的批次大小
    tau: 0                          # 软更新系数
    dd: false                       # 是否使用 double DQN

  test:
    name: "test"
    <<: *common_dqn
    epsilon: 0                      # 贪婪值
