# 环境模型相关路径
new_model:
  torch_model_path: 'C:\Users\admi\Desktop\aaa\model\new\models\端对端_25_0204-0306.pth'
  scaler_x_path: 'C:\Users\admi\Desktop\aaa\model\new\models\scalerx_25_0204-0306.pkl'
  scaler_y_path: 'C:\Users\admi\Desktop\aaa\model\new\models\scalery_25_0204-0306.pkl'

old_model:
  torch_model_path: 'C:\Users\admi\Desktop\aaa\model\old\RF_NOx_Temp.pkl'
  scaler_path: 'C:\Users\admi\Desktop\aaa\model\old\scaler.pkl'

  # 老模型根据动作遍历出来的预测出口浓度表
  model_predict_path: 'C:\Users\admi\Desktop\aaa\data\process\handle\old\model_predict.csv'



# 1. 统计五分钟滞后的浓度
#   - 五分钟之后 real_outlet_c 超出 target_outlet_c 且当前 action < real_action, 异常
#   - 五分钟之后 real_outlet_c 小于 target_outlet_c 且当前 action > real_action, 异常
# 2. 网络结构降低，统计上述结果
# 3. 奖励修改
# 4. 数据集分开测试